#!/usr/bin/env ruby

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), "..", "lib")

require "pruner"

begin
  Pruner.start
rescue SignalException => e
  if Signal.signame(e.signo) == "TERM"
    exit(0)
  else
    raise
  end
rescue
  exit(1)
else
  exit(0)
end
